/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TImage: typeof import('tdesign-vue-next')['Image']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSelectInput: typeof import('tdesign-vue-next')['SelectInput']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTable: typeof import('tdesign-vue-next')['Table']
    TText: typeof import('tdesign-vue-next')['Text']
    TTitle: typeof import('tdesign-vue-next')['Title']
    TTypography: typeof import('tdesign-vue-next')['Typography']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
