export default [
  {
    label: '棉悠悠',
    pinyin: 'mianyouyou',
    alt: '幻兽帕鲁棉悠悠配种公式',
    value: 'Lamball',
    avatar: '/images/Lamball.webp',
    number: '001',
  },
  {
    label: '捣蛋猫',
    pinyin: 'daodanmao',
    alt: '幻兽帕鲁捣蛋猫配种公式',
    value: 'Cattiva',
    avatar: '/images/Cattiva.webp',
    number: '002',
  },
  {
    label: '皮皮鸡',
    pinyin: 'pipiji',
    alt: '幻兽帕鲁皮皮鸡配种公式',
    value: 'Chikipi',
    avatar: '/images/Chikipi.webp',
    number: '003',
  },
  {
    label: '翠叶鼠',
    pinyin: 'cuiyeshu',
    alt: '幻兽帕鲁翠叶鼠配种公式',
    value: 'Lifmunk',
    avatar: '/images/Lifmunk.webp',
    number: '004',
  },
  {
    label: '火绒狐',
    pinyin: 'huoronghu',
    alt: '幻兽帕鲁火绒狐配种公式',
    value: 'Foxparks',
    avatar: '/images/Foxparks.webp',
    number: '005',
  },
  {
    label: '雪绒狐',
    pinyin: 'xueronghu',
    alt: '幻兽帕鲁雪绒狐配种公式',
    value: 'Foxparks-Cryst',
    avatar: '/images/Foxparks-Cryst.webp',
    number: '005B',
  },
  {
    label: '冲浪鸭',
    pinyin: 'chonglangya',
    alt: '幻兽帕鲁冲浪鸭配种公式',
    value: 'Fuack',
    avatar: '/images/Fuack.webp',
    number: '006',
  },
  {
    label: '伏特喵',
    pinyin: 'futemiao',
    alt: '幻兽帕鲁伏特喵配种公式',
    value: 'Sparkit',
    avatar: '/images/Sparkit.webp',
    number: '007',
  },
  {
    label: '新叶猿',
    pinyin: 'xinyeyuan',
    alt: '幻兽帕鲁新叶猿配种公式',
    value: 'Tanzee',
    avatar: '/images/Tanzee.webp',
    number: '008',
  },
  {
    label: '燎火鹿',
    pinyin: 'liaohuolu',
    alt: '幻兽帕鲁燎火鹿配种公式',
    value: 'Rooby',
    avatar: '/images/Rooby.webp',
    number: '009',
  },
  {
    label: '企丸丸',
    pinyin: 'qiwanwang',
    alt: '幻兽帕鲁企丸丸配种公式',
    value: 'Pengullet',
    avatar: '/images/Pengullet.webp',
    number: '010',
  },
  {
    label: '企丸王',
    pinyin: 'qiwanwang',
    alt: '幻兽帕鲁企丸王配种公式',
    value: 'Penking',
    avatar: '/images/Penking.webp',
    number: '011',
  },
  {
    label: '電棘鼠',
    pinyin: 'dianjishu',
    alt: '幻兽帕鲁電棘鼠配种公式',
    value: 'Jolthog',
    avatar: '/images/Jolthog.webp',
    number: '012',
  },
  {
    label: '冰刺鼠',
    pinyin: 'bingcishu',
    alt: '幻兽帕鲁冰刺鼠配种公式',
    value: 'Jolthog-Cryst',
    avatar: '/images/Jolthog-Cryst.webp',
    number: '012B',
  },
  {
    label: '叶泥泥',
    pinyin: 'yenini',
    alt: '幻兽帕鲁叶泥泥配种公式',
    value: 'Gumoss',
    avatar: '/images/Gumoss.webp',
    number: '013',
  },
  {
    label: '玉藻狐',
    pinyin: 'yuzaohu',
    alt: '幻兽帕鲁玉藻狐配种公式',
    value: 'Vixy',
    avatar: '/images/Vixy.webp',
    number: '014',
  },
  {
    label: '啼卡尔',
    pinyin: 'tikaier',
    alt: '幻兽帕鲁啼卡尔配种公式',
    value: 'Hoocrates',
    avatar: '/images/Hoocrates.webp',
    number: '015',
  },
  {
    label: '壶小象',
    pinyin: 'huxiaoxiang',
    alt: '幻兽帕鲁壶小象配种公式',
    value: 'Teafant',
    avatar: '/images/Teafant.webp',
    number: '016',
  },
  {
    label: '瞅什魔',
    pinyin: 'choushimo',
    alt: '幻兽帕鲁瞅什魔配种公式',
    value: 'Depresso',
    avatar: '/images/Depresso.webp',
    number: '017',
  },
  {
    label: '米露菲',
    pinyin: 'milufei',
    alt: '幻兽帕鲁米露菲配种公式',
    value: 'Cremis',
    avatar: '/images/Cremis.webp',
    number: '018',
  },
  {
    label: '寐魔',
    pinyin: 'meimo',
    alt: '幻兽帕鲁寐魔配种公式',
    value: 'Daedream',
    avatar: '/images/Daedream.webp',
    number: '019',
  },
  {
    label: '草莽猪',
    pinyin: 'caomangzhu',
    alt: '幻兽帕鲁草莽猪配种公式',
    value: 'Rushoar',
    avatar: '/images/Rushoar.webp',
    number: '020',
  },
  {
    label: '露娜蒂',
    pinyin: 'lunadi',
    alt: '幻兽帕鲁露娜蒂配种公式',
    value: 'Nox',
    avatar: '/images/Nox.webp',
    number: '021',
  },
  {
    label: '遁地鼠',
    pinyin: 'dundishu',
    alt: '幻兽帕鲁遁地鼠配种公式',
    value: 'Fuddler',
    avatar: '/images/Fuddler.webp',
    number: '022',
  },
  {
    label: '勾魂鱿',
    pinyin: 'gouhunyou',
    alt: '幻兽帕鲁勾魂鱿配种公式',
    value: 'Killamari',
    avatar: '/images/Killamari.webp',
    number: '023',
  },
  {
    label: '喵丝特',
    pinyin: 'miaosite',
    alt: '幻兽帕鲁喵丝特配种公式',
    value: 'Mau',
    avatar: '/images/Mau.webp',
    number: '024',
  },
  {
    label: '冰丝特',
    pinyin: 'bingsite',
    alt: '幻兽帕鲁冰丝特配种公式',
    value: 'Mau-Cryst',
    avatar: '/images/Mau-Cryst.webp',
    number: '024B',
  },
  {
    label: '鲁米儿',
    pinyin: 'lumier',
    alt: '幻兽帕鲁鲁米儿配种公式',
    value: 'Celaray',
    avatar: '/images/Celaray.webp',
    number: '025',
  },
  {
    label: '猎狼',
    pinyin: 'lielang',
    alt: '幻兽帕鲁猎狼配种公式',
    value: 'Direhowl',
    avatar: '/images/Direhowl.webp',
    number: '026',
  },
  {
    label: '炸蛋鸟',
    pinyin: 'zhadanniao',
    alt: '幻兽帕鲁炸蛋鸟配种公式',
    value: 'Tocotoco',
    avatar: '/images/Tocotoco.webp',
    number: '027',
  },
  {
    label: '波娜兔',
    pinyin: 'bonatu',
    alt: '幻兽帕鲁波娜兔配种公式',
    value: 'Flopie',
    avatar: '/images/Flopie.webp',
    number: '028',
  },
  {
    label: '波霸牛',
    pinyin: 'bobaniu',
    alt: '幻兽帕鲁波霸牛配种公式',
    value: 'Mozzarina',
    avatar: '/images/Mozzarina.webp',
    number: '029',
  },
  {
    label: '荊棘魔仙',
    pinyin: 'jingjimoxian',
    alt: '幻兽帕鲁荊棘魔仙配种公式',
    value: 'Bristla',
    avatar: '/images/Bristla.webp',
    number: '030',
  },
  {
    label: '鲨小子',
    pinyin: 'shaxiaozi',
    alt: '幻兽帕鲁鲨小子配种公式',
    value: 'Gobfin',
    avatar: '/images/Gobfin.webp',
    number: '031',
  },
  {
    label: '红小鲨',
    pinyin: 'hongxiaosha',
    alt: '幻兽帕鲁红小鲨配种公式',
    value: 'Gobfin-Ignis',
    avatar: '/images/Gobfin-Ignis.webp',
    number: '031B',
  },
  {
    label: '吊缚灵',
    pinyin: 'diaofuling',
    alt: '幻兽帕鲁吊缚灵配种公式',
    value: 'Hangyu',
    avatar: '/images/Hangyu.webp',
    number: '032',
  },
  {
    label: '冰缚灵',
    pinyin: 'bingfuling',
    alt: '幻兽帕鲁冰缚灵配种公式',
    value: 'Hangyu-Cryst',
    avatar: '/images/Hangyu-Cryst.webp',
    number: '032B',
  },
  {
    label: '叶胖达',
    pinyin: 'yepangda',
    alt: '幻兽帕鲁叶胖达配种公式',
    value: 'Mossanda',
    avatar: '/images/Mossanda.webp',
    number: '033',
  },
  {
    label: '雷胖达',
    pinyin: 'leipangda',
    alt: '幻兽帕鲁雷胖达配种公式',
    value: 'Mossanda-Lux',
    avatar: '/images/Mossanda-Lux.webp',
    number: '033B',
  },
  {
    label: '棉花糖',
    pinyin: 'mianhuatang',
    alt: '幻兽帕鲁棉花糖配种公式',
    value: 'Woolipop',
    avatar: '/images/Woolipop.webp',
    number: '034',
  },
  {
    label: '灌木羊',
    pinyin: 'guanmuyang',
    alt: '幻兽帕鲁灌木羊配种公式',
    value: 'Caprity',
    avatar: '/images/Caprity.webp',
    number: '035',
  },
  {
    label: '郁木羊',
    pinyin: 'yumuyang',
    alt: '幻兽帕鲁郁木羊配种公式',
    value: 'Caprity-Noct',
    avatar: '/images/Caprity-Noct.webp',
    number: '035B',
  },
  {
    label: '美露帕',
    pinyin: 'meilupa',
    alt: '幻兽帕鲁美露帕配种公式',
    value: 'Melpaca',
    avatar: '/images/Melpaca.webp',
    number: '036',
  },
  {
    label: '紫霞鹿',
    pinyin: 'zixialu',
    alt: '幻兽帕鲁紫霞鹿配种公式',
    value: 'Eikthyrdeer',
    avatar: '/images/Eikthyrdeer.webp',
    number: '037',
  },
  {
    label: '祇岳鹿',
    pinyin: 'zhiyuelu',
    alt: '幻兽帕鲁祇岳鹿配种公式',
    value: 'Eikthyrdeer-Terra',
    avatar: '/images/Eikthyrdeer-Terra.webp',
    number: '037B',
  },
  {
    label: '疾风隼',
    pinyin: 'jifengsun',
    alt: '幻兽帕鲁疾风隼配种公式',
    value: 'Nitewing',
    avatar: '/images/Nitewing.webp',
    number: '038',
  },
  {
    label: '姬小兔',
    pinyin: 'jixiaotu',
    alt: '幻兽帕鲁姬小兔配种公式',
    value: 'Ribbuny',
    avatar: '/images/Ribbuny.webp',
    number: '039',
  },
  {
    label: '艾小兔',
    pinyin: 'aixiaotu',
    alt: '幻兽帕鲁艾小兔配种公式',
    value: 'Ribbuny-Botan',
    avatar: '/images/Ribbuny-Botan.webp',
    number: '039B',
  },
  {
    label: '炎魔羊',
    pinyin: 'yanmoyang',
    alt: '幻兽帕鲁炎魔羊配种公式',
    value: 'Incineram',
    avatar: '/images/Incineram.webp',
    number: '040',
  },
  {
    label: '暗魔羊',
    pinyin: 'anmoyang',
    alt: '幻兽帕鲁暗魔羊配种公式',
    value: 'Incineram-Noct',
    avatar: '/images/Incineram-Noct.webp',
    number: '040B',
  },
  {
    label: '幻悦蝶',
    pinyin: 'huanyuedie',
    alt: '幻兽帕鲁幻悦蝶配种公式',
    value: 'Cinnamoth',
    avatar: '/images/Cinnamoth.webp',
    number: '041',
  },
  {
    label: '炽焰牛',
    pinyin: 'chiyanniu',
    alt: '幻兽帕鲁炽焰牛配种公式',
    value: 'Arsox',
    avatar: '/images/Arsox.webp',
    number: '042',
  },
  {
    label: '趴趴鲶',
    pinyin: 'papanian',
    alt: '幻兽帕鲁趴趴鲶配种公式',
    value: 'Dumud',
    avatar: '/images/Dumud.webp',
    number: '043',
  },
  {
    label: '黑鸦隐士',
    pinyin: 'heiyayinshi',
    alt: '幻兽帕鲁黑鸦隐士配种公式',
    value: 'Cawgnito',
    avatar: '/images/Cawgnito.webp',
    number: '044',
  },
  {
    label: '朋克蜥',
    pinyin: 'pengkexi',
    alt: '幻兽帕鲁朋克蜥配种公式',
    value: 'Leezpunk',
    avatar: '/images/Leezpunk.webp',
    number: '045',
  },
  {
    label: '热血蜥',
    pinyin: 'rexuexi',
    alt: '幻兽帕鲁热血蜥配种公式',
    value: 'Leezpunk-Ignis',
    avatar: '/images/Leezpunk-Ignis.webp',
    number: '045B',
  },
  {
    label: '月镰魔',
    pinyin: 'yuelianmo',
    alt: '幻兽帕鲁月镰魔配种公式',
    value: 'Loupmoon',
    avatar: '/images/Loupmoon.webp',
    number: '046',
  },
  {
    label: '霜镰魔',
    pinyin: 'shuanglianmo',
    alt: '幻兽帕鲁霜镰魔配种公式',
    value: 'Loupmoon-Cryst',
    avatar: '/images/Loupmoon-Cryst.webp',
    number: '046B',
  },
  {
    label: '天擒鸟',
    pinyin: 'tianqinniao',
    alt: '幻兽帕鲁天擒鸟配种公式',
    value: 'Galeclaw',
    avatar: '/images/Galeclaw.webp',
    number: '047',
  },
  {
    label: '羽箭射手',
    pinyin: 'yujiansheshou',
    alt: '幻兽帕鲁羽箭射手配种公式',
    value: 'Robinquill',
    avatar: '/images/Robinquill.webp',
    number: '048',
  },
  {
    label: '山岳射手',
    pinyin: 'shanyuesheshou',
    alt: '幻兽帕鲁山岳射手配种公式',
    value: 'Robinquill-Terra',
    avatar: '/images/Robinquill-Terra.webp',
    number: '048B',
  },
  {
    label: '铁拳猿',
    pinyin: 'tiequanyuan',
    alt: '幻兽帕鲁铁拳猿配种公式',
    value: 'Gorirat',
    avatar: '/images/Gorirat.webp',
    number: '049',
  },
  {
    label: '石掌猿',
    pinyin: 'shizhangyuan',
    alt: '幻兽帕鲁石掌猿配种公式',
    value: 'Gorirat-Terra',
    avatar: '/images/Gorirat-Terra.webp',
    number: '049B',
  },
  {
    label: '骑士蜂',
    pinyin: 'qishifeng',
    alt: '幻兽帕鲁骑士蜂配种公式',
    value: 'Beegarde',
    avatar: '/images/Beegarde.webp',
    number: '050',
  },
  {
    label: '女皇蜂',
    pinyin: 'nvhuangfeng',
    alt: '幻兽帕鲁女皇蜂配种公式',
    value: 'Elizabee',
    avatar: '/images/Elizabee.webp',
    number: '051',
  },
  {
    label: '笑魇猫',
    pinyin: 'xiaoyanmao',
    alt: '幻兽帕鲁笑魇猫配种公式',
    value: 'Grintale',
    avatar: '/images/Grintale.webp',
    number: '052',
  },
  {
    label: '毛掸儿',
    pinyin: 'maodaner',
    alt: '幻兽帕鲁毛掸儿配种公式',
    value: 'Swee',
    avatar: '/images/Swee.webp',
    number: '053',
  },
  {
    label: '毛老爹',
    pinyin: 'maolaodie',
    alt: '幻兽帕鲁毛老爹配种公式',
    value: 'Sweepa',
    avatar: '/images/Sweepa.webp',
    number: '054',
  },
  {
    label: '疾旋鼬',
    pinyin: 'jixuanyou',
    alt: '幻兽帕鲁疾旋鼬配种公式',
    value: 'Chillet',
    avatar: '/images/Chillet.webp',
    number: '055',
  },
  {
    label: '桃旋鼬',
    pinyin: 'taoxuanyou',
    alt: '幻兽帕鲁桃旋鼬配种公式',
    value: 'Chillet-Ignis',
    avatar: '/images/Chillet-Ignis.webp',
    number: '055B',
  },
  {
    label: '雷角马',
    pinyin: 'leijiaoma',
    alt: '幻兽帕鲁雷角马配种公式',
    value: 'Univolt',
    avatar: '/images/Univolt.webp',
    number: '056',
  },
  {
    label: '吹雪狐',
    pinyin: 'chuixuehu',
    alt: '幻兽帕鲁吹雪狐配种公式',
    value: 'Foxcicle',
    avatar: '/images/Foxcicle.webp',
    number: '057',
  },
  {
    label: '火麒麟',
    pinyin: 'huoqilin',
    alt: '幻兽帕鲁火麒麟配种公式',
    value: 'Pyrin',
    avatar: '/images/Pyrin.webp',
    number: '058',
  },
  {
    label: '邪麒麟',
    pinyin: 'xielinqi',
    alt: '幻兽帕鲁邪麒麟配种公式',
    value: 'Pyrin-Noct',
    avatar: '/images/Pyrin-Noct.webp',
    number: '058B',
  },
  {
    label: '严冬鹿',
    pinyin: 'yandonglu',
    alt: '幻兽帕鲁严冬鹿配种公式',
    value: 'Reindrix',
    avatar: '/images/Reindrix.webp',
    number: '059',
  },
  {
    label: '霹雳犬',
    pinyin: 'piliqun',
    alt: '幻兽帕鲁霹雳犬配种公式',
    value: 'Rayhound',
    avatar: '/images/Rayhound.webp',
    number: '060',
  },
  {
    label: '苍焰狼',
    pinyin: 'cangyanlang',
    alt: '幻兽帕鲁苍焰狼配种公式',
    value: 'Kitsun',
    avatar: '/images/Kitsun.webp',
    number: '061',
  },
  {
    label: '幽焰狼',
    pinyin: 'youyanlang',
    alt: '幻兽帕鲁幽焰狼配种公式',
    value: 'Kitsun-Noct',
    avatar: '/images/Kitsun-Noct.webp',
    number: '061B',
  },
  {
    label: '雷鸣童子',
    pinyin: 'leimingtongzi',
    alt: '幻兽帕鲁雷鸣童子配种公式',
    value: 'Dazzi',
    avatar: '/images/Dazzi.webp',
    number: '062',
  },
  {
    label: '天阴童子',
    pinyin: 'tianyintongzi',
    alt: '幻兽帕鲁天阴童子配种公式',
    value: 'Dazzi-Noct',
    avatar: '/images/Dazzi-Noct.webp',
    number: '062B',
  },
  {
    label: '秘斯媞雅',
    pinyin: 'misitiya',
    alt: '幻兽帕鲁秘斯媞雅配种公式',
    value: 'Lunaris',
    avatar: '/images/Lunaris.webp',
    number: '063',
  },
  {
    label: '花冠龙',
    pinyin: 'huaguanlong',
    alt: '幻兽帕鲁花冠龙配种公式',
    value: 'Dinossom',
    avatar: '/images/Dinossom.webp',
    number: '064',
  },
  {
    label: '雷冠龙',
    pinyin: 'leiguanlong',
    alt: '幻兽帕鲁雷冠龙配种公式',
    value: 'Dinossom-Lux',
    avatar: '/images/Dinossom-Lux.webp',
    number: '064B',
  },
  {
    label: '滑水蛇',
    pinyin: 'huashuishe',
    alt: '幻兽帕鲁滑水蛇配种公式',
    value: 'Surfent',
    avatar: '/images/Surfent.webp',
    number: '065',
  },
  {
    label: '流沙蛇',
    pinyin: 'liushashe',
    alt: '幻兽帕鲁流沙蛇配种公式',
    value: 'Surfent-Terra',
    avatar: '/images/Surfent-Terra.webp',
    number: '065B',
  },
  {
    label: '噬魂兽',
    pinyin: 'shihunshou',
    alt: '幻兽帕鲁噬魂兽配种公式',
    value: 'Maraith',
    avatar: '/images/Maraith.webp',
    number: '066',
  },
  {
    label: '碎岩龟',
    pinyin: 'suiyangui',
    alt: '幻兽帕鲁碎岩龟配种公式',
    value: 'Digtoise',
    avatar: '/images/Digtoise.webp',
    number: '067',
  },
  {
    label: '猫蝠怪',
    pinyin: 'maofuguai',
    alt: '幻兽帕鲁猫蝠怪配种公式',
    value: 'Tombat',
    avatar: '/images/Tombat.webp',
    number: '068',
  },
  {
    label: '博爱蜥',
    pinyin: 'boaixi',
    alt: '幻兽帕鲁博爱蜥配种公式',
    value: 'Lovander',
    avatar: '/images/Lovander.webp',
    number: '069',
  },
  {
    label: '融焰娘',
    pinyin: 'rongyanniang',
    alt: '幻兽帕鲁融焰娘配种公式',
    value: 'Flambelle',
    avatar: '/images/Flambelle.webp',
    number: '070',
  },
  {
    label: '烽歌龙',
    pinyin: 'fenggelong',
    alt: '幻兽帕鲁烽歌龙配种公式',
    value: 'Vanwyrm',
    avatar: '/images/Vanwyrm.webp',
    number: '071',
  },
  {
    label: '霜歌龙',
    pinyin: 'shuanggelong',
    alt: '幻兽帕鲁霜歌龙配种公式',
    value: 'Vanwyrm-Cryst',
    avatar: '/images/Vanwyrm-Cryst.webp',
    number: '071B',
  },
  {
    label: '浪刃武士',
    pinyin: 'langrenwushi',
    alt: '幻兽帕鲁浪刃武士配种公式',
    value: 'Bushi',
    avatar: '/images/Bushi.webp',
    number: '072',
  },
  {
    label: '鬼刃武士',
    pinyin: 'guirenwushi',
    alt: '幻兽帕鲁鬼刃武士配种公式',
    value: 'Bushi-Noct',
    avatar: '/images/Bushi-Noct.webp',
    number: '072B',
  },
  {
    label: '迅雷鸟',
    pinyin: 'xunleiniao',
    alt: '幻兽帕鲁迅雷鸟配种公式',
    value: 'Beakon',
    avatar: '/images/Beakon.webp',
    number: '073',
  },
  {
    label: '燧火鸟',
    pinyin: 'suihuoniao',
    alt: '幻兽帕鲁燧火鸟配种公式',
    value: 'Ragnahawk',
    avatar: '/images/Ragnahawk.webp',
    number: '074',
  },
  {
    label: '暗巫猫',
    pinyin: 'anwumao',
    alt: '幻兽帕鲁暗巫猫配种公式',
    value: 'Katress',
    avatar: '/images/Katress.webp',
    number: '075',
  },
  {
    label: '炽巫猫',
    pinyin: 'chiwumao',
    alt: '幻兽帕鲁炽巫猫配种公式',
    value: 'Katress-Ignis',
    avatar: '/images/Katress-Ignis.webp',
    number: '075B',
  },
  {
    label: '焰巫狐',
    pinyin: 'yanwuhu',
    alt: '幻兽帕鲁焰巫狐配种公式',
    value: 'Wixen',
    avatar: '/images/Wixen.webp',
    number: '076',
  },
  {
    label: '幽巫狐',
    pinyin: 'youwuhu',
    alt: '幻兽帕鲁幽巫狐配种公式',
    value: 'Wixen-Noct',
    avatar: '/images/Wixen-Noct.webp',
    number: '076B',
  },
  {
    label: '踏春兔',
    pinyin: 'tachuntu',
    alt: '幻兽帕鲁踏春兔配种公式',
    value: 'Verdash',
    avatar: '/images/Verdash.webp',
    number: '077',
  },
  {
    label: '薇莉塔',
    pinyin: 'weilita',
    alt: '幻兽帕鲁薇莉塔配种公式',
    value: 'Vaelet',
    avatar: '/images/Vaelet.webp',
    number: '078',
  },
  {
    label: '绸笠蛾',
    pinyin: 'choulie',
    alt: '幻兽帕鲁绸笠蛾配种公式',
    value: 'Sibelyx',
    avatar: '/images/Sibelyx.webp',
    number: '079',
  },
  {
    label: '精灵龙',
    pinyin: 'jinglinglong',
    alt: '幻兽帕鲁精灵龙配种公式',
    value: 'Elphidran',
    avatar: '/images/Elphidran.webp',
    number: '080',
  },
  {
    label: '水灵龙',
    pinyin: 'shuilinglong',
    alt: '幻兽帕鲁水灵龙配种公式',
    value: 'Elphidran-Aqua',
    avatar: '/images/Elphidran-Aqua.webp',
    number: '080B',
  },
  {
    label: '水灵儿',
    pinyin: 'shuilinger',
    alt: '幻兽帕鲁水灵儿配种公式',
    value: 'Kelpsea',
    avatar: '/images/Kelpsea.webp',
    number: '081',
  },
  {
    label: '火灵儿',
    pinyin: 'huolinger',
    alt: '幻兽帕鲁火灵儿配种公式',
    value: 'Kelpsea-Ignis',
    avatar: '/images/Kelpsea-Ignis.webp',
    number: '081B',
  },
  {
    label: '碧海龙',
    pinyin: 'bihailong',
    alt: '幻兽帕鲁碧海龙配种公式',
    value: 'Azurobe',
    avatar: '/images/Azurobe.webp',
    number: '082',
  },
  {
    label: '冰棘兽',
    pinyin: 'bingjishou',
    alt: '幻兽帕鲁冰棘兽配种公式',
    value: 'Cryolinx',
    avatar: '/images/Cryolinx.webp',
    number: '083',
  },
  {
    label: '金棘兽',
    pinyin: 'jinjishou',
    alt: '幻兽帕鲁金棘兽配种公式',
    value: 'Cryolinx-Terra',
    avatar: '/images/Cryolinx-Terra.webp',
    number: '083B',
  },
  {
    label: '狱焰王',
    pinyin: 'yuyanwang',
    alt: '幻兽帕鲁狱焰王配种公式',
    value: 'Blazehowl',
    avatar: '/images/Blazehowl.webp',
    number: '084',
  },
  {
    label: '狱阎王',
    pinyin: 'yuyanwang',
    alt: '幻兽帕鲁狱阎王配种公式',
    value: 'Blazehowl-Noct',
    avatar: '/images/Blazehowl-Noct.webp',
    number: '084B',
  },
  {
    label: '佩克龙',
    pinyin: 'peikelong',
    alt: '幻兽帕鲁佩克龙配种公式',
    value: 'Relaxaurus',
    avatar: '/images/Relaxaurus.webp',
    number: '085',
  },
  {
    label: '派克龙',
    pinyin: 'paikelong',
    alt: '幻兽帕鲁派克龙配种公式',
    value: 'Relaxaurus-Lux',
    avatar: '/images/Relaxaurus-Lux.webp',
    number: '085B',
  },
  {
    label: '连理龙',
    pinyin: 'lianlilong',
    alt: '幻兽帕鲁连理龙配种公式',
    value: 'Broncherry',
    avatar: '/images/Broncherry.webp',
    number: '086',
  },
  {
    label: '海誓龙',
    pinyin: 'haishilong',
    alt: '幻兽帕鲁海誓龙配种公式',
    value: 'Broncherry-Aqua',
    avatar: '/images/Broncherry-Aqua.webp',
    number: '086B',
  },
  {
    label: '花丽娜',
    pinyin: 'hualina',
    alt: '幻兽帕鲁花丽娜配种公式',
    value: 'Petallia',
    avatar: '/images/Petallia.webp',
    number: '087',
  },
  {
    label: '熔岩兽',
    pinyin: 'rongyanshou',
    alt: '幻兽帕鲁熔岩兽配种公式',
    value: 'Reptyro',
    avatar: '/images/Reptyro.webp',
    number: '088',
  },
  {
    label: '寒霜兽',
    pinyin: 'hanshuangshou',
    alt: '幻兽帕鲁寒霜兽配种公式',
    value: 'Reptyro-Cryst',
    avatar: '/images/Reptyro-Cryst.webp',
    number: '088B',
  },
  {
    label: '君王美露帕',
    pinyin: 'junwangmeilupa',
    alt: '幻兽帕鲁君王美露帕配种公式',
    value: 'Kingpaca',
    avatar: '/images/Kingpaca.webp',
    number: '089',
  },
  {
    label: '冰帝美露帕',
    pinyin: 'bingdimeilupa',
    alt: '幻兽帕鲁冰帝美露帕配种公式',
    value: 'Kingpaca-Cryst',
    avatar: '/images/Kingpaca-Cryst.webp',
    number: '089B',
  },
  {
    label: '森猛犸',
    pinyin: 'senmengma',
    alt: '幻兽帕鲁森猛犸配种公式',
    value: 'Mammorest',
    avatar: '/images/Mammorest.webp',
    number: '090',
  },
  {
    label: '雪猛犸',
    pinyin: 'xuemengma',
    alt: '幻兽帕鲁雪猛犸配种公式',
    value: 'Mammorest-Cryst',
    avatar: '/images/Mammorest-Cryst.webp',
    number: '090B',
  },
  {
    label: '白绒雪怪',
    pinyin: 'bairongxueguai',
    alt: '幻兽帕鲁白绒雪怪配种公式',
    value: 'Wumpo',
    avatar: '/images/Wumpo.webp',
    number: '091',
  },
  {
    label: '绿苔绒怪',
    pinyin: 'lvtairongguai',
    alt: '幻兽帕鲁绿苔绒怪配种公式',
    value: 'Wumpo-Botan',
    avatar: '/images/Wumpo-Botan.webp',
    number: '091B',
  },
  {
    label: '铠格力斯',
    pinyin: 'kaigelisi',
    alt: '幻兽帕鲁铠格力斯配种公式',
    value: 'Warsect',
    avatar: '/images/Warsect.webp',
    number: '092',
  },
  {
    label: '格鲁力斯',
    pinyin: 'gelulisi',
    alt: '幻兽帕鲁格鲁力斯配种公式',
    value: 'Warsect-Terra',
    avatar: '/images/Warsect-Terra.webp',
    number: '092B',
  },
  {
    label: '云海鹿',
    pinyin: 'yunhailu',
    alt: '幻兽帕鲁云海鹿配种公式',
    value: 'Fenglope',
    avatar: '/images/Fenglope.webp',
    number: '093',
  },
  {
    label: '雷隐鹿',
    pinyin: 'leiyinlu',
    alt: '幻兽帕鲁雷隐鹿配种公式',
    value: 'Fenglope-Lux',
    avatar: '/images/Fenglope-Lux.webp',
    number: '093B',
  },
  {
    label: '夜幕魔蝠',
    pinyin: 'yemumofu',
    alt: '幻兽帕鲁夜幕魔蝠配种公式',
    value: 'Felbat',
    avatar: '/images/Felbat.webp',
    number: '094',
  },
  {
    label: '天羽龙',
    pinyin: 'tianyulong',
    alt: '幻兽帕鲁天羽龙配种公式',
    value: 'Quivern',
    avatar: '/images/Quivern.webp',
    number: '095',
  },
  {
    label: '翠羽龙',
    pinyin: 'cuiyulong',
    alt: '幻兽帕鲁翠羽龙配种公式',
    value: 'Quivern-Botan',
    avatar: '/images/Quivern-Botan.webp',
    number: '095B',
  },
  {
    label: '焰煌',
    pinyin: 'yanhuang',
    alt: '幻兽帕鲁焰煌配种公式',
    value: 'Blazamut',
    avatar: '/images/Blazamut.webp',
    number: '096',
  },
  {
    label: '殁殃',
    pinyin: 'moyang',
    alt: '幻兽帕鲁殁殃配种公式',
    value: 'Blazamut-Ryu',
    avatar: '/images/Blazamut-Ryu.webp',
    number: '096B',
  },
  {
    label: '雷冥鸟',
    pinyin: 'leimingniao',
    alt: '幻兽帕鲁雷冥鸟配种公式',
    value: 'Helzephyr',
    avatar: '/images/Helzephyr.webp',
    number: '097',
  },
  {
    label: '雷鸣鸟',
    pinyin: 'leimingniao',
    alt: '幻兽帕鲁雷鸣鸟配种公式',
    value: 'Helzephyr-Lux',
    avatar: '/images/Helzephyr-Lux.webp',
    number: '097B',
  },
  {
    label: '魔渊龙',
    pinyin: 'moyuanlong',
    alt: '幻兽帕鲁魔渊龙配种公式',
    value: 'Astegon',
    avatar: '/images/Astegon.webp',
    number: '098',
  },
  {
    label: '冥铠蝎',
    pinyin: 'mingkaixie',
    alt: '幻兽帕鲁冥铠蝎配种公式',
    value: 'Menasting',
    avatar: '/images/Menasting.webp',
    number: '099',
  },
  {
    label: '金铠蝎',
    pinyin: 'jinkaixie',
    alt: '幻兽帕鲁金铠蝎配种公式',
    value: 'Menasting-Terra',
    avatar: '/images/Menasting-Terra.webp',
    number: '099B',
  },
  {
    label: '阿努比斯',
    pinyin: 'anubisi',
    alt: '幻兽帕鲁阿努比斯配种公式',
    value: 'Anubis',
    avatar: '/images/Anubis.webp',
    number: '100',
  },
  {
    label: '覆海龙',
    pinyin: 'fuhailong',
    alt: '幻兽帕鲁覆海龙配种公式',
    value: 'Jormuntide',
    avatar: '/images/Jormuntide.webp',
    number: '101',
  },
  {
    label: '腾炎龙',
    pinyin: 'tengyanlong',
    alt: '幻兽帕鲁腾炎龙配种公式',
    value: 'Jormuntide-Ignis',
    avatar: '/images/Jormuntide-Ignis.webp',
    number: '101B',
  },
  {
    label: '朱雀',
    pinyin: 'zhuque',
    alt: '幻兽帕鲁朱雀配种公式',
    value: 'Suzaku',
    avatar: '/images/Suzaku.webp',
    number: '102',
  },
  {
    label: '清雀',
    pinyin: 'qingque',
    alt: '幻兽帕鲁清雀配种公式',
    value: 'Suzaku-Aqua',
    avatar: '/images/Suzaku-Aqua.webp',
    number: '102B',
  },
  {
    label: '暴电熊',
    pinyin: 'baodianxiong',
    alt: '幻兽帕鲁暴电熊配种公式',
    value: 'Grizzbolt',
    avatar: '/images/Grizzbolt.webp',
    number: '103',
  },
  {
    label: '百合女王',
    pinyin: 'baihenvwang',
    alt: '幻兽帕鲁百合女王配种公式',
    value: 'Lyleen',
    avatar: '/images/Lyleen.webp',
    number: '104',
  },
  {
    label: '黑月女王',
    pinyin: 'heiyuenvwang',
    alt: '幻兽帕鲁黑月女王配种公式',
    value: 'Lyleen-Noct',
    avatar: '/images/Lyleen-Noct.webp',
    number: '104B',
  },
  {
    label: '荷鲁斯',
    pinyin: 'helusi',
    alt: '幻兽帕鲁荷鲁斯配种公式',
    value: 'Faleris',
    avatar: '/images/Faleris.webp',
    number: '105',
  },
  {
    label: '伊西斯',
    pinyin: 'yixisi',
    alt: '幻兽帕鲁伊西斯配种公式',
    value: 'Faleris-Aqua',
    avatar: '/images/Faleris-Aqua.webp',
    number: '105B',
  },
  {
    label: '波鲁杰克斯',
    pinyin: 'bolujiekesi',
    alt: '幻兽帕鲁波鲁杰克斯配种公式',
    value: 'Orserk',
    avatar: '/images/Orserk.webp',
    number: '106',
  },
  {
    label: '异构格里芬',
    pinyin: 'yigougelifen',
    alt: '幻兽帕鲁异构格里芬配种公式',
    value: 'Shadowbeak',
    avatar: '/images/Shadowbeak.webp',
    number: '107',
  },
  {
    label: '圣光骑士',
    pinyin: 'shengguangqishi',
    alt: '幻兽帕鲁圣光骑士配种公式',
    value: 'Paladius',
    avatar: '/images/Paladius.webp',
    number: '108',
  },
  {
    label: '混沌骑士',
    pinyin: 'hundunqishi',
    alt: '幻兽帕鲁混沌骑士配种公式',
    value: 'Necromus',
    avatar: '/images/Necromus.webp',
    number: '109',
  },
  {
    label: '唤冬兽',
    pinyin: 'huandongshou',
    alt: '幻兽帕鲁唤冬兽配种公式',
    value: 'Frostallion',
    avatar: '/images/Frostallion.webp',
    number: '110',
  },
  {
    label: '唤夜兽',
    pinyin: 'huanyeshou',
    alt: '幻兽帕鲁唤夜兽配种公式',
    value: 'Frostallion-Noct',
    avatar: '/images/Frostallion-Noct.webp',
    number: '110B',
  },
  {
    label: '空涡龙',
    pinyin: 'kongwolong',
    alt: '幻兽帕鲁空涡龙配种公式',
    value: 'Jetragon',
    avatar: '/images/Jetragon.webp',
    number: '111',
  },
  {
    label: '贝菈诺娃',
    pinyin: 'beilanuowa',
    alt: '幻兽帕鲁贝菈诺娃配种公式',
    value: 'Bellanoir',
    avatar: '/images/Bellanoir.webp',
    number: '112',
  },
  {
    label: '贝菈露洁',
    pinyin: 'beilalujie',
    alt: '幻兽帕鲁贝菈露洁配种公式',
    value: 'Bellanoir-Libero',
    avatar: '/images/Bellanoir-Libero.webp',
    number: '112B',
  },
  {
    label: '辉月伊',
    pinyin: 'huiyueyi',
    alt: '幻兽帕鲁辉月伊配种公式',
    value: 'Selyne',
    avatar: '/images/Selyne.webp',
    number: '113',
  },
  {
    label: '武道蛙',
    pinyin: 'wudaowa',
    alt: '幻兽帕鲁武道蛙配种公式',
    value: 'Croajiro',
    avatar: '/images/Croajiro.webp',
    number: '114',
  },
  {
    label: '春彩娘',
    pinyin: 'chuncainiang',
    alt: '幻兽帕鲁春彩娘配种公式',
    value: 'Lullu',
    avatar: '/images/Lullu.webp',
    number: '115',
  },
  {
    label: '菇咚',
    pinyin: 'gudong',
    alt: '幻兽帕鲁菇咚配种公式',
    value: 'Shroomer',
    avatar: '/images/Shroomer.webp',
    number: '116',
  },
  {
    label: '菇波',
    pinyin: 'gubo',
    alt: '幻兽帕鲁菇波配种公式',
    value: 'Shroomer-Noct',
    avatar: '/images/Shroomer-Noct.webp',
    number: '116B',
  },
  {
    label: '球犰',
    pinyin: 'qiuqi',
    alt: '幻兽帕鲁球犰配种公式',
    value: 'Kikit',
    avatar: '/images/Kikit.webp',
    number: '117',
  },
  {
    label: '恐炬灵',
    pinyin: 'kongjuling',
    alt: '幻兽帕鲁恐炬灵配种公式',
    value: 'Sootseer',
    avatar: '/images/Sootseer.webp',
    number: '118',
  },
  {
    label: '蛊刺妖',
    pinyin: 'guciyao',
    alt: '幻兽帕鲁蛊刺妖配种公式',
    value: 'Prixter',
    avatar: '/images/Prixter.webp',
    number: '119',
  },
  {
    label: '泰锋',
    pinyin: 'taifeng',
    alt: '幻兽帕鲁泰锋配种公式',
    value: 'Knocklem',
    avatar: '/images/Knocklem.webp',
    number: '120',
  },
  {
    label: '八云犬',
    pinyin: 'bayunquan',
    alt: '幻兽帕鲁八云犬配种公式',
    value: 'Yakumo',
    avatar: '/images/Yakumo.webp',
    number: '121',
  },
  {
    label: '汪宗师',
    pinyin: 'wangzongshi',
    alt: '幻兽帕鲁汪宗师配种公式',
    value: 'Dogen',
    avatar: '/images/Dogen.webp',
    number: '122',
  },
  {
    label: '战冠雀',
    pinyin: 'zhanguanque',
    alt: '幻兽帕鲁战冠雀配种公式',
    value: 'Dazemu',
    avatar: '/images/Dazemu.webp',
    number: '123',
  },
  {
    label: '旺财',
    pinyin: 'wangcai',
    alt: '幻兽帕鲁旺财配种公式',
    value: 'Mimog',
    avatar: '/images/Mimog.webp',
    number: '124',
  },
  {
    label: '杰诺贝达',
    pinyin: 'jienuobeida',
    alt: '幻兽帕鲁杰诺贝达配种公式',
    value: 'Xenovader',
    avatar: '/images/Xenovader.webp',
    number: '125',
  },
  {
    label: '杰诺路达',
    pinyin: 'jienuoluda',
    alt: '幻兽帕鲁杰诺路达配种公式',
    value: 'Xenogard',
    avatar: '/images/Xenogard.webp',
    number: '126',
  },
  {
    label: '杰诺多兰',
    pinyin: 'jienuoduolan',
    alt: '幻兽帕鲁杰诺多兰配种公式',
    value: 'Xenolord',
    avatar: '/images/Xenolord.webp',
    number: '127',
  },
  {
    label: '魅爱莉',
    pinyin: 'meiaili',
    alt: '幻兽帕鲁魅爱莉配种公式',
    value: 'Nitemary',
    avatar: '/images/Nitemary.webp',
    number: '128',
  },
  {
    label: '夜冥驹',
    pinyin: 'yemingju',
    alt: '幻兽帕鲁夜冥驹配种公式',
    value: 'Starryon',
    avatar: '/images/Starryon.webp',
    number: '129',
  },
  {
    label: '艾基鲁迦',
    pinyin: 'aijilujia',
    alt: '幻兽帕鲁艾基鲁迦配种公式',
    value: 'Silvegis',
    avatar: '/images/Silvegis.webp',
    number: '130',
  },
  {
    label: '墨丸',
    pinyin: 'mowan',
    alt: '幻兽帕鲁墨丸配种公式',
    value: 'Smokie',
    avatar: '/images/Smokie.webp',
    number: '131',
  },
  {
    label: '净世鹿',
    pinyin: 'jingshilu',
    alt: '幻兽帕鲁净世鹿配种公式',
    value: 'Celesdir',
    avatar: '/images/Celesdir.webp',
    number: '132',
  },
  {
    label: '面惧',
    pinyin: 'mianju',
    alt: '幻兽帕鲁面惧配种公式',
    value: 'Omascul',
    avatar: '/images/Omascul.webp',
    number: '133',
  },
  {
    label: '幽恋娜',
    pinyin: 'youlianna',
    alt: '幻兽帕鲁幽恋娜配种公式',
    value: 'Splatterina',
    avatar: '/images/Splatterina.webp',
    number: '134',
  },
  {
    label: '桃蛛娘',
    pinyin: 'taozhuniang',
    alt: '幻兽帕鲁桃蛛娘配种公式',
    value: 'Tarantriss',
    avatar: '/images/Tarantriss.webp',
    number: '135',
  },
  {
    label: '驭雷马',
    pinyin: 'yuleima',
    alt: '幻兽帕鲁驭雷马配种公式',
    value: 'Azurmane',
    avatar: '/images/Azurmane.webp',
    number: '136',
  },
  {
    label: '霜牙王',
    pinyin: 'shuangyawang',
    alt: '幻兽帕鲁霜牙王配种公式',
    value: 'Bastigor',
    avatar: '/images/Bastigor.webp',
    number: '137',
  },
  {
    label: '梅莉姆',
    pinyin: 'meilimu',
    alt: '幻兽帕鲁梅莉姆配种公式',
    value: 'Prunelia',
    avatar: '/images/Prunelia.webp',
    number: '138',
  },
  {
    label: '妮瞅莎',
    pinyin: 'nichousha',
    alt: '幻兽帕鲁妮瞅莎配种公式',
    value: 'Nyafia',
    avatar: '/images/Nyafia.webp',
    number: '139',
  },
  {
    label: '金驰兽',
    pinyin: 'jinchishou',
    alt: '幻兽帕鲁金驰兽配种公式',
    value: 'Gildane',
    avatar: '/images/Gildane.webp',
    number: '140',
  },
]
